title: Jang BeomJun
author: GitHub User
email: tjtdkr@naver.com
description: > # this means to ignore newlines until "show_exerpts:"

show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Jang BeomJun, tjtdkr
  tagline: Student, who want to be a developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
  disqus_shortname: tech

  # generate social links in footer
  social_links:
    facebook: 장범준
    github: tjtdkr
    instagram: tjtdkr
    rss: 
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

...
comments: true
...
